#ifndef HIBROWSER_TYPE_H
#define HIBROWSER_TYPE_H

#include <map>
#include <string>

enum PlatformMessage {
    MESSAGE_LOADING_PROGRESS,
    MESSAGE_HISTORY_CHANGED,
    MESSAGE_CREATE_THUMBNAIL,
    MESSAGE_REMOVE_SPEEDDIAL,
    MESSAGE_MOVE_SPEEDDIAL,
    MESSAGE_ADD_SPEEDDIAL,
    MESSAGE_GET_SPEEDDIAL,
    MESSAGE_GET_HISTORY,
    MESSAGE_GET_ALL_BOOKMARKS,
    MESSAGE_GET_CUROSR_POSITON,
    MESSAGE_GET_WINDOW_SIZE,
    MESSAGE_GET_SCROLL,
    MESSAGE_TOP_MARGIN_REACHED,
    MESSAGE_SCROLL_PAGE,
    MESSAGE_CAPTURE_THUMBNAIL,
    MESSAGE_LOADING_FINISHED,
    MESSAGE_LOADING_STARTED,
    MESSAGE_EVENT_ADDED_TAB,
    MESSAGE_GET_TAB_TITLE,
    MESSAGE_DELETE_HISTORY,
    MESSAGE_GET_ZOOM,
    MESSAGE_CLEAR_ALL_HISTORY,
    MESSAGE_VIDEO_FULLSCREEN_CHANGE,
    MESSAGE_VIDEO_PLAYED,
    MESSAGE_VIDEO_BACKWARD,
    MESSAGE_VIDEO_PLAYPAUSE,
    MESSAGE_VIDEO_STOP,
    MESSAGE_VIDEO_FORWARD,
    MESSAGE_VIDEO_PAUSED,
    MESSAGE_VIDEO_WAITING,
    MESSAGE_VIDEO_PLAYING,
    MESSAGE_VIDEO_ENDED,
    MESSAGE_VIDEO_TIME_UPDATE,
    MESSAGE_VIDEO_SET_PERCENTAGE,
    MESSAGE_GET_SPEEDDIAL_BY_URL,
    MESSAGE_GET_VIRTUAL_KEYBOARD_STATUS,
    MESSAGE_VIDEO_EXIT_FULLSCREEN,
    MESSAGE_VIDEO_PLAY,
    MESSAGE_VIDEO_PAUSE,
    MESSAGE_EVENT_TAB_ACTIVATED,
    MESSAGE_EVENT_REMOVE_TAB
};

typedef std::map<PlatformMessage, std::string> BrowserMessages;
static BrowserMessages messagesMap;

#define MESSAGES_MAP_INSERT_ITEM( key, value ) \
    messagesMap.insert( std::make_pair( key, value ) )

#define MESSAGES_MAP_INIT() \
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_LOADING_PROGRESS,     "loadingprogress" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_HISTORY_CHANGED,      "historychanged" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_CREATE_THUMBNAIL,     "createThumbnailForUrl" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_REMOVE_SPEEDDIAL,     "removeSpeedDial" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_MOVE_SPEEDDIAL,       "moveSpeedDial" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_ADD_SPEEDDIAL,        "addSpeedDial" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_GET_SPEEDDIAL,        "getSpeedDials" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_GET_HISTORY,          "getHistory" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_GET_ALL_BOOKMARKS,    "getAllBookmarks" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_GET_CUROSR_POSITON,   "getCursorPosition" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_GET_WINDOW_SIZE,      "getWindowSize" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_GET_SCROLL,           "getScroll" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_TOP_MARGIN_REACHED,   "topmarginreached" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_SCROLL_PAGE,          "scrollpage" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_CAPTURE_THUMBNAIL,    "captureThumbnail" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_LOADING_FINISHED,     "loadingfinished" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_LOADING_STARTED,      "loadingstarted" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_EVENT_ADDED_TAB,      "tabadded" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_GET_TAB_TITLE,        "getTabTitle" );\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_DELETE_HISTORY,       "deleteHistory");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_GET_ZOOM,             "getZoomFactor");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_CLEAR_ALL_HISTORY,    "clearHistory");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_FULLSCREEN_CHANGE, "videoFSChanged");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_PLAYED,         "videoPlayed");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_BACKWARD,       "videoBackward");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_PLAYPAUSE,      "videoPlayPause");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_STOP,           "videoStop");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_FORWARD,        "videoForward");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_PAUSED,         "videoPaused");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_PLAYING,        "videoPlaying");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_WAITING,        "videoWaiting");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_ENDED,          "videoEnded");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_TIME_UPDATE,    "videoTimeUpdate");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_SET_PERCENTAGE, "videoSetPercentage");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_GET_SPEEDDIAL_BY_URL, "getSpeedDialByUrl");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_GET_VIRTUAL_KEYBOARD_STATUS, "getVirtualKeyBoardStatus");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_EXIT_FULLSCREEN, "videoExitFullScreen");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_PLAY,           "videoPlay");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_VIDEO_PAUSE,          "videoPause");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_EVENT_TAB_ACTIVATED,  "tabactivated");\
    MESSAGES_MAP_INSERT_ITEM( MESSAGE_EVENT_REMOVE_TAB,     "tabremoved");\



std::string getMessageStringValue( PlatformMessage key )
{
    std::string value;
    BrowserMessages::iterator it = messagesMap.find( key );
    if ( it == messagesMap.end() )
    {
        value = "error";
    }
    else
    {
        value = it->second;
    }

    return value;
}

#endif